// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type SchemaMigrations struct {
	Version string `json:"version"`
}

type Todo struct {
	ID           int64        `json:"id"`
	Content      string       `json:"content"`
	Done         bool         `json:"done"`
	Creationdate sql.NullTime `json:"creationdate"`
}
