// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID           int64        `json:"id"`
	Content      string       `json:"content"`
	Done         bool         `json:"done"`
	CreationDate sql.NullTime `json:"creationDate"`
}
