// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddTask(arg1:string):Promise<db.Todo>;

export function GetTasks():Promise<Array<db.Todo>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTask(arg1:number):Promise<db.Todo>;

export function TickTask(arg1:boolean,arg2:number):Promise<db.Todo>;
