// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['App']['AddTask'](arg1);
}

export function CloseApp() {
  return window['go']['main']['App']['CloseApp']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function TickTask(arg1, arg2) {
  return window['go']['main']['App']['TickTask'](arg1, arg2);
}
